STELLAR_BURGERS_URL = 'https://stellarburgers.nomoreparties.site/'
REGISTRATION_URL = 'https://stellarburgers.nomoreparties.site/register'
AUTHORIZATION_URL = 'https://stellarburgers.nomoreparties.site/login'
FEED_URL = 'https://stellarburgers.nomoreparties.site/feed'
FORGOT_PASSWORD_URL = 'https://stellarburgers.nomoreparties.site/forgot-password'
PROFILE_URL = 'https://stellarburgers.nomoreparties.site/account/profile'
ORDER_HISTORY = 'https://stellarburgers.nomoreparties.site/account/order-history'
